### ISSUE TITLE
Analyse data

### ISSUE THREAD

**Issue by Capital2** [Capital2/Big-M#5]
take the last iteration and interpret data
should return a dict?

**Comment by SBJ2000** [comment]
The last iteration will be a matrix? If yes, then we should just analyse its lines and return messages that contains the interpretations, isn't it?

**Comment by Capital2** [comment]
The front should take care of creating those messages, I still don't know what to do with this function hhhh

**Comment by Seif-edd** [comment]
i thought we should take every iterations and test if its possible to make variations ( compare variation with contraints)
thoughts?

**Comment by Capital2** [comment]
> i thought we should take every iterations and test if its possible to make variations ( compare variation with contraints) thoughts?

7kina 3leha lfaza, l'analyse de sensibilité has so many variables to implement ken t7eb edda5alha:
- fama des contraintes izidou
- fama des contraintes yon9sou
- fama fonction objectif aslan yetbadlou (kima jeb fel ds)
- ...
this function wa9telli 3malt el issue mechi fibeli analyse de sensibilité, mbaad 9olna zeyed 5alleha analyse 3adiya wakahw

**Comment by Seif-edd** [comment]
ena kaaed nekhdem feha mtaa l contrainte tetabdel 
nkamel walee?

**Comment by Capital2** [comment]
Barra bro yaatik essa7a
