### ISSUE TITLE
Create function FormatUserInput

### ISSUE THREAD

**Issue by achrafoo2018** [Capital2/Big-M#7]
```
def FormatUserInput(userInput : list[str]) -> list[list[int]]:
    """
    The function takes an array of strings representing the input taken and **validated** from a jupyter user.
    The function returns a matrix.
    Arguments:
        userInput : array of string
    Returns:
        Matrix following the format shown in the output image bellow
    """
```

Input Example:

-      Max Z = 2x+3y

-      3x+y <= 2

-      x-y > 3

Output: 

![image](https://user-images.githubusercontent.com/43815739/200143663-71155675-a42b-4b8c-8f7f-280f456c8704.png)

PS: 

- Take care of multiple spaces.
- UpperCase, LowerCase.
- The input is already validated

**Comment by Capital2** [comment]
Updated flags in #21
